export const albumsData = [
	{ userId: 1, id: 1, title: "Мой первый альбом" },
	{ userId: 1, id: 2, title: "Летние воспоминания" },
	{ userId: 1, id: 3, title: "Фото с работы" },
	{ userId: 1, id: 4, title: "Природа вокруг" },
	{ userId: 1, id: 5, title: "Путешествия" },
	{ userId: 1, id: 6, title: "Вечер с друзьями" },
	{ userId: 1, id: 7, title: "Мои питомцы" },
	{ userId: 1, id: 8, title: "Городские улицы" },
	{ userId: 1, id: 9, title: "Спорт и активность" },
	{ userId: 1, id: 10, title: "Семейные праздники" },
	{ userId: 2, id: 11, title: "Воспоминания детства" },
	{ userId: 2, id: 12, title: "Любимые книги" },
	{ userId: 2, id: 13, title: "Фото с концертов" },
	{ userId: 2, id: 14, title: "Пейзажи" },
	{ userId: 2, id: 15, title: "Творчество и хобби" },
	{ userId: 2, id: 16, title: "Рабочие моменты" },
	{ userId: 2, id: 17, title: "Друзья и встречи" },
	{ userId: 2, id: 18, title: "Вечерние прогулки" },
	{ userId: 2, id: 19, title: "Семейные ужины" },
	{ userId: 2, id: 20, title: "Романтические моменты" },
	{ userId: 3, id: 21, title: "Путешествия за границу" },
	{ userId: 3, id: 22, title: "Море и пляж" },
	{ userId: 3, id: 23, title: "Горы и походы" },
	{ userId: 3, id: 24, title: "Фото еды" },
	{ userId: 3, id: 25, title: "Культурные мероприятия" },
	{ userId: 3, id: 26, title: "Музыка и концерты" },
	{ userId: 3, id: 27, title: "Домашние питомцы" },
	{ userId: 3, id: 28, title: "Фотографии с работы" },
	{ userId: 3, id: 29, title: "Спорт и активный отдых" },
	{ userId: 3, id: 30, title: "Природа и пейзажи" },
	{ userId: 4, id: 31, title: "Семейные фотографии" },
	{ userId: 4, id: 32, title: "Друзья и вечеринки" },
	{ userId: 4, id: 33, title: "Любимые места" },
	{ userId: 4, id: 34, title: "Творчество и хобби" },
	{ userId: 4, id: 35, title: "Праздники" },
	{ userId: 4, id: 36, title: "Рабочие моменты" },
	{ userId: 4, id: 37, title: "Прогулки по городу" },
	{ userId: 4, id: 38, title: "Фото друзей" },
	{ userId: 4, id: 39, title: "Спорт и фитнес" },
	{ userId: 4, id: 40, title: "Природа" },
	{ userId: 5, id: 41, title: "Семейные моменты" },
	{ userId: 5, id: 42, title: "Путешествия" },
	{ userId: 5, id: 43, title: "Вечер с друзьями" },
	{ userId: 5, id: 44, title: "Хобби и творчество" },
	{ userId: 5, id: 45, title: "Фото еды" },
	{ userId: 5, id: 46, title: "Любимые книги" },
	{ userId: 5, id: 47, title: "Концерты и музыка" },
	{ userId: 5, id: 48, title: "Путешествия" },
	{ userId: 5, id: 49, title: "Друзья и встречи" },
	{ userId: 5, id: 50, title: "Спорт и активность" },
	{ userId: 6, id: 51, title: "Мои питомцы" },
	{ userId: 6, id: 52, title: "Рабочие моменты" },
	{ userId: 6, id: 53, title: "Творчество и хобби" },
	{ userId: 6, id: 54, title: "Природа и прогулки" },
	{ userId: 6, id: 55, title: "Вечерние прогулки" },
	{ userId: 6, id: 56, title: "Фото друзей" },
	{ userId: 6, id: 57, title: "Семейные праздники" },
	{ userId: 6, id: 58, title: "Любимые книги" },
	{ userId: 6, id: 59, title: "Концерты и музыка" },
	{ userId: 6, id: 60, title: "Спорт и активность" },
	{ userId: 7, id: 61, title: "Путешествия за границу" },
	{ userId: 7, id: 62, title: "Море и пляж" },
	{ userId: 7, id: 63, title: "Горы и походы" },
	{ userId: 7, id: 64, title: "Фото еды" },
	{ userId: 7, id: 65, title: "Культурные мероприятия" },
	{ userId: 7, id: 66, title: "Музыка и концерты" },
	{ userId: 7, id: 67, title: "Домашние питомцы" },
	{ userId: 7, id: 68, title: "Фотографии с работы" },
	{ userId: 7, id: 69, title: "Спорт и активный отдых" },
	{ userId: 7, id: 70, title: "Природа и пейзажи" },
	{ userId: 8, id: 71, title: "Семейные фотографии" },
	{ userId: 8, id: 72, title: "Друзья и вечеринки" },
	{ userId: 8, id: 73, title: "Любимые места" },
	{ userId: 8, id: 74, title: "Творчество и хобби" },
	{ userId: 8, id: 75, title: "Праздники" },
	{ userId: 8, id: 76, title: "Рабочие моменты" },
	{ userId: 8, id: 77, title: "Прогулки по городу" },
	{ userId: 8, id: 78, title: "Фото друзей" },
	{ userId: 8, id: 79, title: "Спорт и фитнес" },
	{ userId: 8, id: 80, title: "Природа" },
	{ userId: 9, id: 81, title: "Семейные моменты" },
	{ userId: 9, id: 82, title: "Путешествия" },
	{ userId: 9, id: 83, title: "Вечер с друзьями" },
	{ userId: 9, id: 84, title: "Хобби и творчество" },
	{ userId: 9, id: 85, title: "Фото еды" },
	{ userId: 9, id: 86, title: "Любимые книги" },
	{ userId: 9, id: 87, title: "Концерты и музыка" },
	{ userId: 9, id: 88, title: "Путешествия" },
	{ userId: 9, id: 89, title: "Друзья и встречи" },
	{ userId: 9, id: 90, title: "Спорт и активность" },
	{ userId: 10, id: 91, title: "Мои питомцы" },
	{ userId: 10, id: 92, title: "Рабочие моменты" },
	{ userId: 10, id: 93, title: "Творчество и хобби" },
	{ userId: 10, id: 94, title: "Природа и прогулки" },
	{ userId: 10, id: 95, title: "Вечерние прогулки" },
	{ userId: 10, id: 96, title: "Фото друзей" },
	{ userId: 10, id: 97, title: "Семейные праздники" },
	{ userId: 10, id: 98, title: "Любимые книги" },
	{ userId: 10, id: 99, title: "Концерты и музыка" },
	{ userId: 10, id: 100, title: "Спорт и активность" },
]
